-- Migration 007: Add nombre field to ideas table
-- Created: 2025-11-06
-- Description: Add descriptive name field for ideas (generated by AI)

-- Add nombre column to ideas table
ALTER TABLE ideas
ADD COLUMN IF NOT EXISTS nombre TEXT;

-- Add comment explaining the field
COMMENT ON COLUMN ideas.nombre IS 'Descriptive project name generated by AI (e.g., "Bonds Fintech", "Booking App - Barberías")';

-- Success message
DO $$
BEGIN
  RAISE NOTICE 'Migration 007 completed successfully: Added nombre field to ideas table';
END $$;
