"use client";

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileCode2, Calendar, Files, ArrowLeft } from 'lucide-react';

interface Theme {
  id: string;
  name: string;
  description: string;
  preview_path: string;
  created_at: string;
  file_count: number;
}

export default function ThemesPage() {
  const [themes, setThemes] = useState<Theme[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchThemes() {
      try {
        const response = await fetch('/api/themes');
        const data = await response.json();
        if (data.success) {
          setThemes(data.data);
        }
      } catch (error) {
        console.error('Error fetching themes:', error);
      } finally {
        setLoading(false);
      }
    }

    fetchThemes();
  }, []);

  if (loading) {
    return (
      <div className="container mx-auto py-8">
        <p>Loading themes...</p>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-8 space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link href="/projects">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-3xl font-bold">Design Themes</h1>
            <p className="text-muted-foreground mt-2">
              Style guides and design systems generated by /design-system
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {themes.map((theme) => (
          <Card key={theme.id} className="hover:shadow-lg transition-shadow">
            <CardHeader>
              <div className="flex items-start justify-between">
                <FileCode2 className="h-10 w-10 text-primary mb-2" />
                <span className="text-xs text-muted-foreground">{theme.id}</span>
              </div>
              <CardTitle>{theme.name}</CardTitle>
              <CardDescription className="line-clamp-2">
                {theme.description}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center gap-4 text-sm text-muted-foreground">
                <div className="flex items-center gap-1">
                  <Files className="h-4 w-4" />
                  <span>{theme.file_count} files</span>
                </div>
                <div className="flex items-center gap-1">
                  <Calendar className="h-4 w-4" />
                  <span>{new Date(theme.created_at).toLocaleDateString()}</span>
                </div>
              </div>

              <Link href={`/themes/${theme.id}`}>
                <Button className="w-full">
                  View Theme
                </Button>
              </Link>
            </CardContent>
          </Card>
        ))}
      </div>

      {themes.length === 0 && (
        <div className="text-center py-12">
          <FileCode2 className="h-16 w-16 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-semibold mb-2">No themes yet</h3>
          <p className="text-muted-foreground">
            Run /design-system to create your first theme
          </p>
        </div>
      )}
    </div>
  );
}
